application: jieblog
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/x-icon

- url: /images
  static_dir: images

- url: /icons
  static_dir: icons

- url: /swf
  static_dir: swf

- url: /stylesheets
  static_dir: stylesheets

- url: /rich_text_editor
  static_dir: rich_text_editor

- url: /.*
  script: main.py
