application: jieblog
version: 3
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/x-icon

- url: /images
  static_dir: images
  
- url: /images
  static_dir: images
  
- url: /rpc_relay.html
  static_files: static/rpc_relay.html
  upload: static/rpc_relay.html

- url: /canvas.html
  static_files: static/canvas.html
  upload: static/canvas.html
  
- url: /player
  static_files: static/player.html
  upload: static/player.html

- url: /xnplayer.xml
  static_files: static/xnplayer.xml
  upload: static/xnplayer.xml
  
- url: /xnplayer.html
  static_files: static/xnplayer.html
  upload: static/xnplayer.html
  
- url: /test.html
  static_files: static/test.html
  upload: static/test.html
  
- url: /icons
  static_dir: icons

- url: /swf
  static_dir: swf

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /.*
  script: main.py