application: jieblog
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico
  mime_type: image/x-icon

- url: /images
  static_dir: images
  
- url: /images
  static_dir: images
  
- url: /rpc_relay.html
  static_files: static/rpc_relay.html
  upload: static/rpc_relay.html

- url: /canvas.html
  static_files: static/canvas.html
  upload: static/canvas.html 
  
- url: /icons
  static_dir: icons

- url: /swf
  static_dir: swf

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /rich_text_editor
  static_dir: rich_text_editor

- url: /.*
  script: main.py
